stages:
    - deploy

variables:
    ANSIBLE_HOSTS_IP: "15.236.35.86"
    ANSIBLE_USER_HOST: "ubuntu"

deploy-job:
    stage: deploy
    image: python-3.11.slim
    script:
        - echo "Install Ansible"
        - python3 -m pip install --user ansible
        - ansible --version
