stages:
    - deploy

deploy-job:
    stage: deploy
    image: python:3.11-slim
    script:
        - apt-get update && apt-get install -y openssh-client sshpass git wget gnupg

        - echo "Install Terraform"
        - wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list
        - apt update && apt install terraform

        - echo "Install Ansible"
        - python3 -m pip install --user ansible
        # Добавляем /root/.local/bin в переменную окружения PATH
        - export PATH="/root/.local/bin:$PATH"
        
        - git clone https://github.com/Bohdan14228/iac-aws.git
        - cd iac-aws
        - terraform init
        - terraform plan
        - terraform apply -auto-remove
        - export INSTANCE_IP=$(terraform output -raw instance_public_ip) 
        - cd ..

        - echo "Configuring SSH key..."
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - # Добавление ключа в ssh-agent

        - echo "Add host to inventory..."
        - cd ansible
        - echo "[webserver]" >> ./inventory.ini
        - echo "$INSTANCE_IP ansible_user=ubuntu ansible_port=22 ansible_ssh_private_key_file=~/iac-aws/terraform_pem" >> ./inventory.ini
        - echo "Running Ansible Playbook..."

        - export ANSIBLE_HOST_KEY_CHECKING=False #говорим ансиблу чтобы убрал фингерпринт
        - ansible-playbook -i inventory.ini setup.yaml -l webserver   #--tags webserver - для выбора тасков
  
    only:
        - main